### ISSUE TITLE
Tour of BioMixer

### ISSUE THREAD

**Issue by everbeek** [thechiselgroup/biomixer#495]
Is there a web app oriented thing similar to Tours that we could use to guide new users?

**Comment by everbeek** [comment]
I asked Laura, and she directed me to this: http://tourmyapp.com/

I will look at it, and search for alternatives now that I have this lead.

**Comment by everbeek** [comment]
A free jquery plugin under MIT license: http://zurb.com/playground/jquery-joyride-feature-tour-plugin

**Comment by cpetrachenko** [comment]
Great ideas and I'm excited to do something like this. But do tools like these affect the performance of the application being described?

**Comment by everbeek** [comment]
I don't think they would affect performance. They would only be activated on first visit or via some "Show Me!" button that I would add. Nothing in the existing functionality would trigger any of a tour library's code, only vice versa and only  during a tour. It would increase the download size, but that's unlikely to be a problem for quite some time.

**Comment by everbeek** [comment]
Some thoughts:
- I really want to be able to execute arbitrary JS at each step. If whatever I pick does not support it, I will modify to include pre- and post- function calls
- I also need to be able to provide functions rather than strings for data ids that any tour uses to position dialogs
- I also want to be able to inspect the tour data for ids to be used, and verify that they exist whenever possible. The use of this is so that I can see during development if I have broken part of the tour, reducing the chance I will do so prior to committing it. If I use functions to get ids, that implies they may not be present at the time of page load, which complicates this requirement. Perhaps I have to skip verifying the presence of those ids.

**Comment by everbeek** [comment]
For the tour, if I don't think I can do it using whatever graph the user has loaded, I can set it up to be a link to a stand alone window, which is passed an argument that starts the tour right away.

**Comment by everbeek** [comment]
Ok, pulling the trigger on intro.js. If I have problems with it, Joyride and Hopscotch are both options too.

**Comment by everbeek** [comment]
I set up a tour with intro.js, but it allows popups to be positioned such that they go off screen. That's not ok, and there is a long outstanding issue for it. I will set things up with Joyride next, and probably Hopscotch. If it seems like the right decision, I will devise a fix for Intro.js and probably submit a pull request.

**Comment by everbeek** [comment]
Intro.js doesn't allow use of highlighted elements, which means the users cannot perform the actions I want them to. I haven't completely abandoned it, since this might be easier to modify than Hopscotch...

Hopscotch does let me have users actually use page elements, but it doesn't offer shading, or modal dialogs, or non-anchored ones (where there is no target for it to point to). It also allows dialogs to fall off screen.

**Comment by everbeek** [comment]
I have disabled spotlighting and shading because of the SVG incompatibility. I now have null exception spawning from the same overall problem.

**Comment by everbeek** [comment]
Introjs steps behave well know, until I need the menu opened up. Then the tooltip causes the page to expand wider, and it gets placed off to the right of the menu item of interest, even pointing in the wrong direction. It is as though it is being added with incorrect display properties or to the wrong parent element, but it is likely something else.

**Comment by everbeek** [comment]
getBoundingClientRect() is giving me decent values for most elements, except those that are nested in my menu.

**Comment by everbeek** [comment]
Have it all working now. Committing, then adding id checks at construction time, and getting on to fixing a bug wherein I cannot drag nodes. I think it preceded this work.

**Comment by everbeek** [comment]
Add:
- arc color and ontology color can be re-assigned by clicking on the sample arc in the arc filter menu, or on the color swatch in the ontology filter menu

**Comment by everbeek** [comment]
I am considering re-implementing the Intro.Js highlight mechanism (which I disabled with CSS). If I make it into four lines, rather than a box proper, then we can click through it freely in any browser.

**Comment by everbeek** [comment]
I have an outline that works with html and SVG. It can be improved visually later via CSS, but works well as it is. It cannot be given a background, because that would lead us back to the same problem that I was trying to resolve.

Also got myself stuck when I changed a function to a lambda function and failed to change a single call instance...couldn't figure out why the menu system was broken. Sorted it out though.

**Comment by everbeek** [comment]
Looks great in embed. Closing case for now, but tweaks will surely follow later.
