### ISSUE TITLE
Iconify More Buttons

### ISSUE THREAD

**Issue by everbeek** [thechiselgroup/biomixer#496]
I have more icons to add. The ascii +/- for filter menu collapses. The menu itself can be replaced with a toggle triple line icon I have available, or with some drop and pull-up icons. I have question mark icons I can use for toggling help perhap. Add these and it will look way more professional.

Also, create a hover over class for the icons, to enhance user perception of them as buttons.

Icons from https://useiconic.com/open/, but can also check http://fortawesome.github.io/Font-Awesome/icons/

**Comment by everbeek** [comment]
Should the menu be these, toggled appropriately:
![expand-down-8x](https://cloud.githubusercontent.com/assets/2280053/5762571/c232614e-9c97-11e4-947b-dd085f76f342.png)
![expand-up-8x](https://cloud.githubusercontent.com/assets/2280053/5762572/c3bdbdb0-9c97-11e4-92ab-5bbde7ccad7c.png)

Or this:

![menu-8x](https://cloud.githubusercontent.com/assets/2280053/5762576/c8bea540-9c97-11e4-8e0e-081c5255bfed.png)

The three line menu one looks just like that used in plenty of other programs. It seems more appropriate.

**Comment by cpetrachenko** [comment]
Triple it!

**Comment by everbeek** [comment]
Have I ever mentioned I hate CSS? I have the menu icon added, and recolored when the menu is closed, to draw some more attention to it. I had trouble getting the text label and icon sorted out.

**Comment by everbeek** [comment]
Have I ever mentioned I hate CSS? I have the menu icon added, and recolored when the menu is closed, to draw some more attention to it. I had trouble getting the text label and icon sorted out.

**Comment by everbeek** [comment]
Trying out those expand/collapse icons instead of +/- for the submenus.

**Comment by cpetrachenko** [comment]
Hmmm, bad. I think we should return to the simple +/-.

**Comment by everbeek** [comment]
![old expanders](https://cloud.githubusercontent.com/assets/2280053/5768930/409beb54-9cca-11e4-9848-b2368c8e5d65.JPG)

becomes:

![new expanders](https://cloud.githubusercontent.com/assets/2280053/5768933/4687d19a-9cca-11e4-8146-07176c30dabd.JPG)

**Comment by everbeek** [comment]
![old buttons](https://cloud.githubusercontent.com/assets/2280053/5805929/a45ffdb4-9fc8-11e4-85aa-b0e27f4e1233.JPG)
![new buttons](https://cloud.githubusercontent.com/assets/2280053/5805931/a6561932-9fc8-11e4-9150-9344bb6d3949.JPG)

**Comment by everbeek** [comment]
Making adjustments...changing order of Layout and Node Utilities. Making Node Utilities minimized by default. Making the first ontology expanded by default. Making "Add Concept By URI" into a simple box, then that button, plus the larger associated text as a tool tip. Changing target icon to also have "Locate" text adjacent to it.

**Comment by everbeek** [comment]
Done all those changes.

**Comment by everbeek** [comment]
Unless Cassie or I identifies an icon for Add Concept Using URI, this issue is closed.
